global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: "ganggpt-app"
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ["app:4828"]
    
  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
