# GangGPT Kubernetes Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganggpt-backend
  labels:
    app: ganggpt
    component: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: ganggpt
      component: backend
  template:
    metadata:
      labels:
        app: ganggpt
        component: backend
    spec:
      containers:
      - name: backend
        image: ganggpt/backend:latest        ports:
        - containerPort: 4828
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "4828"
        - name: POSTGRES_HOST
          value: "ganggpt-postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_USER
          value: "ganggpt"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ganggpt-secrets
              key: postgres-password
        - name: POSTGRES_DB
          value: "ganggpt_production"
        - name: REDIS_HOST
          value: "ganggpt-redis"
        - name: REDIS_PORT
          value: "6379"
        - name: REDIS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ganggpt-secrets
              key: redis-password
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: ganggpt-secrets
              key: jwt-secret
        - name: JWT_REFRESH_SECRET
          valueFrom:
            secretKeyRef:
              name: ganggpt-secrets
              key: jwt-refresh-secret
        - name: AZURE_OPENAI_ENDPOINT
          value: "https://ganggpt-ai.openai.azure.com/"
        - name: AZURE_OPENAI_API_KEY
          valueFrom:
            secretKeyRef:
              name: ganggpt-secrets
              key: azure-openai-key
        resources:
          requests:
            memory: "512Mi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "500m"        livenessProbe:
          httpGet:
            path: /api/health/liveness
            port: 4828
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health/readiness
            port: 4828
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ganggpt-backend-service
  labels:
    app: ganggpt
    component: backend
spec:  type: ClusterIP
  ports:
  - port: 4828
    targetPort: 4828
    protocol: TCP
  selector:
    app: ganggpt
    component: backend
