# GangGPT Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ganggpt-frontend
  labels:
    app: ganggpt
    component: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ganggpt
      component: frontend
  template:
    metadata:
      labels:
        app: ganggpt
        component: frontend
    spec:
      containers:
      - name: frontend
        image: ganggpt/frontend:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.ganggpt.com"
        - name: NEXTAUTH_URL
          value: "https://ganggpt.com"
        - name: NEXTAUTH_SECRET
          valueFrom:
            secretKeyRef:
              name: ganggpt-secrets
              key: nextauth-secret
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ganggpt-frontend-service
  labels:
    app: ganggpt
    component: frontend
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  selector:
    app: ganggpt
    component: frontend
